/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeLogin;
import org.rodrigodiaz.model.Login;

/**
 *
 * @author rodro
 */
public class LoginVeterinaryProject extends javax.swing.JFrame {
    
    /***
     * Cremos un objeto instanciado del controlador
     */
    private ControlDeLogin controlador = ControlDeLogin.getInstancia();
    
    VentanaClientVeterinary viewClientVeterinary = new VentanaClientVeterinary();
    VentanaAdminVeterinary viewAdminVeterinary = new VentanaAdminVeterinary();

    /**
     * Creates new form LoginVeterinaryProject
     */
    public LoginVeterinaryProject() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_nameVeterinary = new javax.swing.JLabel();
        lbl_fondoLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtPassLogin = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        txtUsuarioLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgroundLogin.setBackground(new java.awt.Color(255, 255, 255));
        backgroundLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/logoVeterinaria3.png"))); // NOI18N
        backgroundLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        lbl_nameVeterinary.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_nameVeterinary.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nameVeterinary.setText("VETERINARIA KINAL");
        backgroundLogin.add(lbl_nameVeterinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        lbl_fondoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/city.png"))); // NOI18N
        lbl_fondoLogo.setText("jLabel2");
        backgroundLogin.add(lbl_fondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 290, 490));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/login.png"))); // NOI18N
        jLabel4.setText("LOGIN");
        backgroundLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 50));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INICIAR SESIÓN");
        backgroundLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("USUARIO");
        backgroundLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        backgroundLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 370, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        backgroundLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 370, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CONTRASEÑA");
        backgroundLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtPassLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtPassLogin.setText("***************");
        txtPassLogin.setBorder(null);
        txtPassLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassLoginMousePressed(evt);
            }
        });
        backgroundLogin.add(txtPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 360, -1));

        botonIngresar.setBackground(new java.awt.Color(0, 134, 190));
        botonIngresar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("INGRESAR");
        botonIngresar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        backgroundLogin.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 110, 40));

        txtUsuarioLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioLogin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuarioLogin.setText("Ingrese su nombre de usuario");
        txtUsuarioLogin.setToolTipText("");
        txtUsuarioLogin.setBorder(null);
        txtUsuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioLoginMousePressed(evt);
            }
        });
        backgroundLogin.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 390, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioLoginMousePressed
        if (txtUsuarioLogin.getText().equals("Ingrese su nombre de usuario")){
            txtUsuarioLogin.setText("");
            txtUsuarioLogin.setForeground(Color.black);
        }
      
        
    }//GEN-LAST:event_txtUsuarioLoginMousePressed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String cI = "123";
        String uI = "admin";
        /*int cantidadElementos = controlador.cantidadDeLogin();
        for (int i = 0; i < cantidadElementos; i++) {
            Login login = controlador.listaDeLogin().get(i);
            if (txtUsuarioLogin.getText().equals(controlador.cantidadDeLogin())) {
                viewAdminVeterinary.setVisible(true);

            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto");
            }
            
        }*/
        if (uI.equals(txtUsuarioLogin.getText()) && cI.equals(String.valueOf(txtPassLogin.getPassword()))) {
            viewAdminVeterinary.setVisible(true);
 
        }else if(txtUsuarioLogin.getText() != "admin" && String.valueOf(txtPassLogin.getPassword())!= "123"){
            viewClientVeterinary.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña o Usuario incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

        
        
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void txtPassLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassLoginMousePressed
        if (String.valueOf(txtPassLogin.getPassword()).equals("***************")){
            txtPassLogin.setText("");
            txtPassLogin.setForeground(Color.black);
        }

    }//GEN-LAST:event_txtPassLoginMousePressed

/**/
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundLogin;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_fondoLogo;
    private javax.swing.JLabel lbl_nameVeterinary;
    private javax.swing.JPasswordField txtPassLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
