/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeCliente;
import org.rodrigodiaz.model.Cliente;

/**
 *
 * @author rodro
 */
public class ViewVerCliente extends javax.swing.JInternalFrame {
    private ControlDeCliente controlador = ControlDeCliente.getInstancia();

    /**
     * Creates new form ViewVerUsuarios
     */
    public ViewVerCliente() {
        initComponents();
        mostrarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        botonVerClientes = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ver Clientes");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Cliente", "Nombre", "Apellido", "Telefono", "Email", "DPI", "Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(tablaDeClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 650, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER CLIENTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 170, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 510, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCliente3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        botonVerClientes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerClientes.setForeground(new java.awt.Color(0, 0, 0));
        botonVerClientes.setText("ACEPTAR");
        botonVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerClientesActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerClientesActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerClientesActionPerformed

    
    private void mostrarClientes(){
        int cantidadDeElementos = controlador.cantidadDeClientes();
        String [] encabezado = {"Id", "Nombre", "Apellido", "Telefono", "Email", "DPI", "Usuario", "Contraseña"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeClientes.setModel(cabecera);
        TableModel tablaDeClientesVista = tablaDeClientes.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            Cliente cliente = controlador.listaDeClientes().get(i);
            tablaDeClientes.setValueAt(cliente.getIdCliente(), i, 0);
            tablaDeClientes.setValueAt(cliente.getNombreCliente(), i, 1);
            tablaDeClientes.setValueAt(cliente.getApellidoCliente(), i, 2);
            tablaDeClientes.setValueAt(cliente.getTelefonoCliente(), i, 3);
            tablaDeClientes.setValueAt(cliente.getEmailCliente(), i, 4);
            tablaDeClientes.setValueAt(cliente.getDpiCliente(), i, 5);
            tablaDeClientes.setValueAt(cliente.getUsuarioCliente(), i, 6);
            tablaDeClientes.setValueAt(cliente.getContraseñaCliente(), i, 7);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeClientes;
    // End of variables declaration//GEN-END:variables
}
