/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeDoctor;
import org.rodrigodiaz.model.Doctor;

/**
 *
 * @author rodro
 */
public class ViewActualizarDoctor extends javax.swing.JInternalFrame {
            ControlDeDoctor controlador = new ControlDeDoctor();


    /**
     * Creates new form ViewActualizarMedico
     */
    public ViewActualizarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidoMedico = new javax.swing.JLabel();
        lblTelefonoMedico = new javax.swing.JLabel();
        lblDIreccionMedico = new javax.swing.JLabel();
        lblIdBuscarEliminarMedico = new javax.swing.JLabel();
        lblDepartamentoMedico = new javax.swing.JLabel();
        ckkEstadoMedico = new javax.swing.JCheckBox();
        lblEstadoMedico = new javax.swing.JLabel();
        lblEspecialidadMedico = new javax.swing.JLabel();
        cbDepartamentoMedico = new javax.swing.JComboBox<>();
        txtIdBuscarActualizarMedico = new javax.swing.JTextField();
        txtApellidoMedico = new javax.swing.JTextField();
        txtEspecialidadMedico = new javax.swing.JTextField();
        txtDireccionMedico = new javax.swing.JTextField();
        txtTelefonoMedico = new javax.swing.JTextField();
        botonCancelarActualizarMedico = new javax.swing.JButton();
        lblNombreMedico1 = new javax.swing.JLabel();
        txtNombreMedico = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonActualizar = new javax.swing.JButton();
        botonBuscarDoctor = new javax.swing.JButton();

        setClosable(true);
        setTitle("Actualizar Medico");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTUALIZAR MEDICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoMedico3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 310, -1));

        lblApellidoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblApellidoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoMedico.setText("Apellido");
        jPanel1.add(lblApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        lblTelefonoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoMedico.setText("Telefono");
        jPanel1.add(lblTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, -1));

        lblDIreccionMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDIreccionMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDIreccionMedico.setText("Direccion");
        jPanel1.add(lblDIreccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 60, -1));

        lblIdBuscarEliminarMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblIdBuscarEliminarMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblIdBuscarEliminarMedico.setText("Id a buscar");
        jPanel1.add(lblIdBuscarEliminarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));

        lblDepartamentoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDepartamentoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamentoMedico.setText("Departamento");
        jPanel1.add(lblDepartamentoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 100, -1));

        ckkEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ckkEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        ckkEstadoMedico.setText("Activo");
        jPanel1.add(ckkEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 70, -1));

        lblEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMedico.setText("Estado");
        jPanel1.add(lblEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        lblEspecialidadMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEspecialidadMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEspecialidadMedico.setText("Especialidad");
        jPanel1.add(lblEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, -1));

        cbDepartamentoMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Peten", "Quetzaltenango", "Quiche", "Retalhuleu", "Sacatepequez", "San Marcos", "Santa Rosa", "Solola", "Suchitepequez", "Totonicapan", "Zacapa" }));
        jPanel1.add(cbDepartamentoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, -1));
        jPanel1.add(txtIdBuscarActualizarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));
        jPanel1.add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));
        jPanel1.add(txtEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, -1));
        jPanel1.add(txtDireccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 130, -1));
        jPanel1.add(txtTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 130, -1));

        botonCancelarActualizarMedico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarActualizarMedico.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarActualizarMedico.setText("CANCELAR");
        botonCancelarActualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActualizarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelarActualizarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 130, 30));

        lblNombreMedico1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMedico1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMedico1.setText("Nombre");
        jPanel1.add(lblNombreMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, -1));
        jPanel1.add(txtNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        botonActualizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizar.setText("ACTUALIZAR");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 140, 30));

        botonBuscarDoctor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarDoctor.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarDoctor.setText("BUSCAR");
        botonBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActualizarMedicoActionPerformed
        txtIdBuscarActualizarMedico.setText("");
        txtNombreMedico.setText("");
        txtApellidoMedico.setText("");
        txtTelefonoMedico.setText("");
        txtDireccionMedico.setText("");
        txtEspecialidadMedico.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActualizarMedicoActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        Doctor doctor = new Doctor();
        doctor.setIdDoctor(Integer.parseInt(txtIdBuscarActualizarMedico.getText()));
        doctor.setNombreDoctor(txtNombreMedico.getText());
        doctor.setApellidoDoctor(txtApellidoMedico.getText());
        doctor.setTelefonoDoctor(txtTelefonoMedico.getText());
        doctor.setDireccionDoctor(txtDireccionMedico.getText());
        
        if (cbDepartamentoMedico.getSelectedItem().equals("Alta Verapaz")) {
            doctor.setIdDepartamento(1);
        }else if(cbDepartamentoMedico.getSelectedItem().equals("Baja Verapaz")){
            doctor.setIdDepartamento(2);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Chimaltenango")) {
            doctor.setIdDepartamento(3);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Chiquimula")) {
            doctor.setIdDepartamento(4);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("El Progreso")) {
            doctor.setIdDepartamento(5);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Escuintla")) {
            doctor.setIdDepartamento(6);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Guatemala")) {
            doctor.setIdDepartamento(7);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Huehuetenango")) {
            doctor.setIdDepartamento(8);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Izabal")) {
            doctor.setIdDepartamento(9);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Jalapa")) {
            doctor.setIdDepartamento(10);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Jutiapa")) {
            doctor.setIdDepartamento(11);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Peten")) {
            doctor.setIdDepartamento(12);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Quetzaltenango")) {
            doctor.setIdDepartamento(13);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Quiche")) {
            doctor.setIdDepartamento(14);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Retalhuleu")) {
            doctor.setIdDepartamento(15);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Sacatepequez")) {
            doctor.setIdDepartamento(16);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("San Marcos")) {
            doctor.setIdDepartamento(17);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Santa Rosa")) {
            doctor.setIdDepartamento(18);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Solola")) {
            doctor.setIdDepartamento(19);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Suchitepequez")) {
            doctor.setIdDepartamento(20);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Totonicapan")) {
            doctor.setIdDepartamento(21);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Zacapa")) {
            doctor.setIdDepartamento(22);
        }
        
        doctor.setEspecialidadDoctor(txtEspecialidadMedico.getText());
       if (ckkEstadoMedico.isSelected()) {
            doctor.setEstadoActivo(true);
        }else{
            doctor.setEstadoActivo(false);
        }      
        
       controlador.actualizarDoctor(doctor);
        
        txtIdBuscarActualizarMedico.setText("");
        txtNombreMedico.setText("");
        txtApellidoMedico.setText("");
        txtTelefonoMedico.setText("");
        txtDireccionMedico.setText("");
        txtEspecialidadMedico.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDoctorActionPerformed
        Doctor doctor = new Doctor();
        doctor.setIdDoctor(Integer.parseInt(txtIdBuscarActualizarMedico.getText()));
        doctor = controlador.buscarCliente(doctor);
        if (doctor != null) {
            txtNombreMedico.setText(doctor.getNombreDoctor());
            txtApellidoMedico.setText(doctor.getApellidoDoctor());
            txtTelefonoMedico.setText(doctor.getTelefonoDoctor());
            txtDireccionMedico.setText(doctor.getDireccionDoctor());
            txtEspecialidadMedico.setText(doctor.getEspecialidadDoctor());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBuscarDoctor;
    private javax.swing.JButton botonCancelarActualizarMedico;
    private javax.swing.JComboBox<String> cbDepartamentoMedico;
    private javax.swing.JCheckBox ckkEstadoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApellidoMedico;
    private javax.swing.JLabel lblDIreccionMedico;
    private javax.swing.JLabel lblDepartamentoMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblEstadoMedico;
    private javax.swing.JLabel lblIdBuscarEliminarMedico;
    private javax.swing.JLabel lblNombreMedico1;
    private javax.swing.JLabel lblTelefonoMedico;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtDireccionMedico;
    private javax.swing.JTextField txtEspecialidadMedico;
    private javax.swing.JTextField txtIdBuscarActualizarMedico;
    private javax.swing.JTextField txtNombreMedico;
    private javax.swing.JTextField txtTelefonoMedico;
    // End of variables declaration//GEN-END:variables
}
