/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeDoctor;
import org.rodrigodiaz.model.Doctor;

/**
 *
 * @author rodro
 */
public class ViewEliminarDoctor extends javax.swing.JInternalFrame {
            ControlDeDoctor controlador = new ControlDeDoctor();


    /**
     * Creates new form ViewEliminarMedico
     */
    public ViewEliminarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidoMedico = new javax.swing.JLabel();
        lblTelefonoMedico = new javax.swing.JLabel();
        lblDIreccionMedico = new javax.swing.JLabel();
        lblIdBuscarEliminarMedico = new javax.swing.JLabel();
        lblDepartamentoMedico = new javax.swing.JLabel();
        ckkEstadoMedico = new javax.swing.JCheckBox();
        lblEstadoMedico = new javax.swing.JLabel();
        lblEspecialidadMedico = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtIdBuscarEliminarMedico = new javax.swing.JTextField();
        txtApellidoMedico = new javax.swing.JTextField();
        txtEspecialidadMedico = new javax.swing.JTextField();
        txtDireccionMedico = new javax.swing.JTextField();
        txtTelefonoMedico = new javax.swing.JTextField();
        botonCancelarEliminarMedico = new javax.swing.JButton();
        lblNombreMedico1 = new javax.swing.JLabel();
        txtNombreMedico1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonEliminarMedico = new javax.swing.JButton();
        botonBuscarDoctor = new javax.swing.JButton();

        setClosable(true);
        setTitle("Eliminar Medico");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ELIMINAR MEDICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoMedico3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 310, -1));

        lblApellidoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblApellidoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoMedico.setText("Apellido");
        jPanel1.add(lblApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        lblTelefonoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoMedico.setText("Telefono");
        jPanel1.add(lblTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, -1));

        lblDIreccionMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDIreccionMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDIreccionMedico.setText("Direccion");
        jPanel1.add(lblDIreccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 60, -1));

        lblIdBuscarEliminarMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblIdBuscarEliminarMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblIdBuscarEliminarMedico.setText("Id a buscar");
        jPanel1.add(lblIdBuscarEliminarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));

        lblDepartamentoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDepartamentoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamentoMedico.setText("Departamento");
        jPanel1.add(lblDepartamentoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 100, -1));

        ckkEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ckkEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        ckkEstadoMedico.setText("Activo");
        jPanel1.add(ckkEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 70, -1));

        lblEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMedico.setText("Estado");
        jPanel1.add(lblEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        lblEspecialidadMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEspecialidadMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEspecialidadMedico.setText("Especialidad");
        jPanel1.add(lblEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Peten", "Quetzaltenango", "Quiche", "Retalhuleu", "Sacatepequez", "San Marcos", "Santa Rosa", "Solola", "Suchitepequez", "Totonicapan", "Zacapa" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, -1));
        jPanel1.add(txtIdBuscarEliminarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));
        jPanel1.add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, -1));
        jPanel1.add(txtEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, -1));
        jPanel1.add(txtDireccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 130, -1));
        jPanel1.add(txtTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 130, -1));

        botonCancelarEliminarMedico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarEliminarMedico.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarEliminarMedico.setText("CANCELAR");
        botonCancelarEliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarEliminarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelarEliminarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 130, 30));

        lblNombreMedico1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMedico1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMedico1.setText("Nombre");
        jPanel1.add(lblNombreMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, -1));
        jPanel1.add(txtNombreMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        botonEliminarMedico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonEliminarMedico.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminarMedico.setText("ELIMINAR");
        botonEliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 120, 30));

        botonBuscarDoctor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarDoctor.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarDoctor.setText("BUSCAR");
        botonBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarEliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarEliminarMedicoActionPerformed
        txtNombreMedico1.setText("");
        txtApellidoMedico.setText("");
        txtTelefonoMedico.setText("");
        txtDireccionMedico.setText("");
        txtEspecialidadMedico.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarEliminarMedicoActionPerformed

    private void botonEliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMedicoActionPerformed
        Doctor doctor = new Doctor();
        doctor.setIdDoctor(Integer.parseInt(txtIdBuscarEliminarMedico.getText()));
        controlador.ocultarDoctor(doctor);
        
        txtNombreMedico1.setText("");
        txtApellidoMedico.setText("");
        txtTelefonoMedico.setText("");
        txtDireccionMedico.setText("");
        txtEspecialidadMedico.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonEliminarMedicoActionPerformed

    private void botonBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDoctorActionPerformed
        Doctor doctor = new Doctor();
        doctor.setIdDoctor(Integer.parseInt(txtIdBuscarEliminarMedico.getText()));
        doctor = controlador.buscarCliente(doctor);
        if (doctor != null) {
            txtNombreMedico1.setText(doctor.getNombreDoctor());
            txtApellidoMedico.setText(doctor.getApellidoDoctor());
            txtTelefonoMedico.setText(doctor.getTelefonoDoctor());
            txtDireccionMedico.setText(doctor.getDireccionDoctor());
            txtEspecialidadMedico.setText(doctor.getEspecialidadDoctor());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarDoctor;
    private javax.swing.JButton botonCancelarEliminarMedico;
    private javax.swing.JButton botonEliminarMedico;
    private javax.swing.JCheckBox ckkEstadoMedico;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApellidoMedico;
    private javax.swing.JLabel lblDIreccionMedico;
    private javax.swing.JLabel lblDepartamentoMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblEstadoMedico;
    private javax.swing.JLabel lblIdBuscarEliminarMedico;
    private javax.swing.JLabel lblNombreMedico1;
    private javax.swing.JLabel lblTelefonoMedico;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtDireccionMedico;
    private javax.swing.JTextField txtEspecialidadMedico;
    private javax.swing.JTextField txtIdBuscarEliminarMedico;
    private javax.swing.JTextField txtNombreMedico1;
    private javax.swing.JTextField txtTelefonoMedico;
    // End of variables declaration//GEN-END:variables
}
