/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeDetalleCD;
import org.rodrigodiaz.model.DetalleCD;

/**
 *
 * @author rodro
 */
public class ViewVerDetalleCD extends javax.swing.JInternalFrame {
    
    private ControlDeDetalleCD controlador = ControlDeDetalleCD.getInstancia();

    /**
     * Creates new form ViewVerDetalleCD
     */
    public ViewVerDetalleCD() {
        initComponents();
        mostrarDetalleCD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeDetalleCD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonVerMascotas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ver Detalle Cita Doctor");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeDetalleCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Mascota", "Nombre", "Raza", "Color", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaDeDetalleCD);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 600, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER DETALLE CITA DOCTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 240, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 510, 10));

        botonVerMascotas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerMascotas.setForeground(new java.awt.Color(0, 0, 0));
        botonVerMascotas.setText("ACEPTAR");
        botonVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMascotasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoDetalle2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMascotasActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerMascotasActionPerformed

    
    private void mostrarDetalleCD(){
        int cantidadDeElementos = controlador.cantidadDeDetalles();
        String [] encabezado = {"Id Detalle", "Id Cita", "Id Doctor", "Id Servicios"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeDetalleCD.setModel(cabecera);
        TableModel tablaDeDetallesVista = tablaDeDetalleCD.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            DetalleCD detalle = controlador.listaDeDetalles().get(i);
            tablaDeDetalleCD.setValueAt(detalle.getIdDetalleCD(), i, 0);
            tablaDeDetalleCD.setValueAt(detalle.getIdCita(), i, 1);
            tablaDeDetalleCD.setValueAt(detalle.getIdDoctor(), i, 2);
            tablaDeDetalleCD.setValueAt(detalle.getIdServicios(), i, 3);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerMascotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeDetalleCD;
    // End of variables declaration//GEN-END:variables
}
