
package org.rodrigodiaz.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeCita;
import org.rodrigodiaz.model.Cita;

/**
 *
 * @author rodro
 */
public class ViewActualizarCita extends javax.swing.JInternalFrame {
            ControlDeCita controlador = new ControlDeCita();

    /**
     * Creates new form ViewActualizarCita
     */
    public ViewActualizarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearCita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNombreMascotaCita = new javax.swing.JLabel();
        lblFechaCita = new javax.swing.JLabel();
        lblServicioCita = new javax.swing.JLabel();
        lblHoraCita = new javax.swing.JLabel();
        lblNombreDueñoCita = new javax.swing.JLabel();
        lblEmailCita = new javax.swing.JLabel();
        lblTelefonoCita = new javax.swing.JLabel();
        lblDpiCita = new javax.swing.JLabel();
        lblNitCita = new javax.swing.JLabel();
        botonCancelarActualizarCita = new javax.swing.JButton();
        txtFechaCita = new javax.swing.JTextField();
        txtHoraCita = new javax.swing.JTextField();
        txtIdBuscarActualizarCita = new javax.swing.JTextField();
        txtNitCita = new javax.swing.JTextField();
        txtNombreDueñoCita = new javax.swing.JTextField();
        txtEmailCita = new javax.swing.JTextField();
        txtTelefonoCita = new javax.swing.JTextField();
        txtDpiCita = new javax.swing.JTextField();
        cbServicioCita = new javax.swing.JComboBox<>();
        lblFechaCita1 = new javax.swing.JLabel();
        txtNombreMascotaCita1 = new javax.swing.JTextField();
        botonActualizarCita = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        botonBuscarCita = new javax.swing.JButton();

        setClosable(true);
        setTitle("Actualizar Cita");

        panelCrearCita.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTUALIZAR CITA");
        panelCrearCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCita2.png"))); // NOI18N
        panelCrearCita.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        panelCrearCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 510, 10));

        lblNombreMascotaCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascotaCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascotaCita.setText("Nombre Mascota");
        panelCrearCita.add(lblNombreMascotaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, -1));

        lblFechaCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCita.setText("Id a buscar");
        panelCrearCita.add(lblFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, -1));

        lblServicioCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblServicioCita.setForeground(new java.awt.Color(0, 0, 0));
        lblServicioCita.setText("Servicio");
        panelCrearCita.add(lblServicioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        lblHoraCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblHoraCita.setForeground(new java.awt.Color(0, 0, 0));
        lblHoraCita.setText("Hora");
        panelCrearCita.add(lblHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        lblNombreDueñoCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreDueñoCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreDueñoCita.setText("Nombre Dueño");
        panelCrearCita.add(lblNombreDueñoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, -1));

        lblEmailCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEmailCita.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailCita.setText("Email");
        panelCrearCita.add(lblEmailCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));

        lblTelefonoCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoCita.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoCita.setText("Telefono");
        panelCrearCita.add(lblTelefonoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, -1));

        lblDpiCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDpiCita.setForeground(new java.awt.Color(0, 0, 0));
        lblDpiCita.setText("DPI");
        panelCrearCita.add(lblDpiCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, -1));

        lblNitCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNitCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNitCita.setText("Nit");
        panelCrearCita.add(lblNitCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, -1));

        botonCancelarActualizarCita.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarActualizarCita.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarActualizarCita.setText("CANCELAR");
        botonCancelarActualizarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActualizarCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonCancelarActualizarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 130, 30));

        txtFechaCita.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaCita.setText("AAAA/MM/DD");
        txtFechaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaCitaMousePressed(evt);
            }
        });
        txtFechaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, -1));

        txtHoraCita.setForeground(new java.awt.Color(0, 0, 0));
        txtHoraCita.setText("HH/MM/SS");
        txtHoraCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHoraCitaMousePressed(evt);
            }
        });
        panelCrearCita.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, -1));
        panelCrearCita.add(txtIdBuscarActualizarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 130, -1));
        panelCrearCita.add(txtNitCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 130, -1));
        panelCrearCita.add(txtNombreDueñoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));
        panelCrearCita.add(txtEmailCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, -1));
        panelCrearCita.add(txtTelefonoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 130, -1));
        panelCrearCita.add(txtDpiCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 130, -1));

        cbServicioCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anestesiologo", "Cardiologia", "Cirugia", "Dermatologia", "Fisioterapia", "Neurologia", "Oftalmologia", "Oncologia", "Ortopedia", "Equinos" }));
        panelCrearCita.add(cbServicioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 130, -1));

        lblFechaCita1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblFechaCita1.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCita1.setText("Fecha");
        panelCrearCita.add(lblFechaCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));
        panelCrearCita.add(txtNombreMascotaCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, -1));

        botonActualizarCita.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizarCita.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizarCita.setText("ACTUALIZAR");
        botonActualizarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonActualizarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 140, 30));
        panelCrearCita.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 510, 10));

        botonBuscarCita.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarCita.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarCita.setText("BUSCAR");
        botonBuscarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonBuscarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActualizarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActualizarCitaActionPerformed
        txtIdBuscarActualizarCita.setText("");
        txtFechaCita.setText("");
        txtHoraCita.setText("");
        txtNombreMascotaCita1.setText("");
        txtNombreDueñoCita.setText("");
        txtEmailCita.setText("");
        txtTelefonoCita.setText("");
        txtDpiCita.setText("");
        txtNitCita.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActualizarCitaActionPerformed

    private void txtFechaCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaCitaMousePressed
        if (txtFechaCita.getText().equals("AAAA/MM/DD")) {
            txtFechaCita.setText("");
            txtFechaCita.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaCitaMousePressed

    private void txtHoraCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraCitaMousePressed
        if (txtHoraCita.getText().equals("HH/MM/SS")) {
            txtHoraCita.setText("");
            txtHoraCita.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtHoraCitaMousePressed

    private void botonActualizarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarCitaActionPerformed
        Cita cita = new Cita();
        cita.setIdCita(Integer.parseInt(txtIdBuscarActualizarCita.getText()));
        cita.setFechaCita(txtFechaCita.getText());
        cita.setHoraCita(txtHoraCita.getText());
        cita.setNombreMascotaCita(txtNombreMascotaCita1.getText());
        cita.setNombreDueñoCita(txtNombreDueñoCita.getText());
        cita.setEmailDueñoCita(txtEmailCita.getText());
        cita.setTelefonoDueñoCita(txtTelefonoCita.getText());
        
         if (cbServicioCita.getSelectedItem().equals("Anestesiologo")) {
            cita.setIdServicioCita(1);
        }else if(cbServicioCita.getSelectedItem().equals("Cardiologia")){
            cita.setIdServicioCita(2);
        }else if(cbServicioCita.getSelectedItem().equals("Cirugia")){
            cita.setIdServicioCita(3);
        }else if(cbServicioCita.getSelectedItem().equals("Dermatologia")){
            cita.setIdServicioCita(4);
        }else if(cbServicioCita.getSelectedItem().equals("Fisioterapia")){
            cita.setIdServicioCita(5);
        }else if(cbServicioCita.getSelectedItem().equals("Neurologia")){
            cita.setIdServicioCita(6);
        }else if(cbServicioCita.getSelectedItem().equals("Oftalmologia")){
            cita.setIdServicioCita(7);
        }else if(cbServicioCita.getSelectedItem().equals("Oncologia")){
            cita.setIdServicioCita(8);
        }else if(cbServicioCita.getSelectedItem().equals("Ortopedia")){
            cita.setIdServicioCita(9);
        }else if(cbServicioCita.getSelectedItem().equals("Equinos")){
            cita.setIdServicioCita(10);
        }
         
         cita.setDpiDueñoCita(txtDpiCita.getText());
         cita.setNitDueñoCita(txtNitCita.getText());
         cita.setCostoCita(100f);
         cita.setEstado(true);
         controlador.actualizarCita(cita);
        

        txtIdBuscarActualizarCita.setText("");
        txtFechaCita.setText("");
        txtHoraCita.setText("");
        txtNombreMascotaCita1.setText("");
        txtNombreDueñoCita.setText("");
        txtEmailCita.setText("");
        txtTelefonoCita.setText("");
        txtDpiCita.setText("");
        txtNitCita.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonActualizarCitaActionPerformed

    private void botonBuscarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCitaActionPerformed
        Cita cita = new Cita();
        cita.setIdCita(Integer.parseInt(txtIdBuscarActualizarCita.getText()));
        cita = controlador.buscarCita(cita);
        if (cita != null) {
            txtFechaCita.setText(cita.getFechaCita());
            txtHoraCita.setText(cita.getHoraCita());
            txtNombreMascotaCita1.setText(cita.getNombreMascotaCita());
            txtNombreDueñoCita.setText(cita.getNombreDueñoCita());
            txtEmailCita.setText(cita.getEmailDueñoCita());
            txtTelefonoCita.setText(cita.getTelefonoDueñoCita());
            txtDpiCita.setText(cita.getDpiDueñoCita());
            txtNitCita.setText(cita.getNitDueñoCita());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarCitaActionPerformed

    private void txtFechaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCita;
    private javax.swing.JButton botonBuscarCita;
    private javax.swing.JButton botonCancelarActualizarCita;
    private javax.swing.JComboBox<String> cbServicioCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDpiCita;
    private javax.swing.JLabel lblEmailCita;
    private javax.swing.JLabel lblFechaCita;
    private javax.swing.JLabel lblFechaCita1;
    private javax.swing.JLabel lblHoraCita;
    private javax.swing.JLabel lblNitCita;
    private javax.swing.JLabel lblNombreDueñoCita;
    private javax.swing.JLabel lblNombreMascotaCita;
    private javax.swing.JLabel lblServicioCita;
    private javax.swing.JLabel lblTelefonoCita;
    private javax.swing.JPanel panelCrearCita;
    private javax.swing.JTextField txtDpiCita;
    private javax.swing.JTextField txtEmailCita;
    private javax.swing.JTextField txtFechaCita;
    private javax.swing.JTextField txtHoraCita;
    private javax.swing.JTextField txtIdBuscarActualizarCita;
    private javax.swing.JTextField txtNitCita;
    private javax.swing.JTextField txtNombreDueñoCita;
    private javax.swing.JTextField txtNombreMascotaCita1;
    private javax.swing.JTextField txtTelefonoCita;
    // End of variables declaration//GEN-END:variables
}
