/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeDetalleCM;
import org.rodrigodiaz.model.DetalleCM;

/**
 *
 * @author rodro
 */
public class ViewVerDetalleCM extends javax.swing.JInternalFrame {
    
    private ControlDeDetalleCM controlador = ControlDeDetalleCM.getInstancia();

    /**
     * Creates new form ViewVerDetalleCM
     */
    public ViewVerDetalleCM() {
        initComponents();
        mostrarDetalleCM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeDetalleCM = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonVerMascotas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ver Detalle Cliente Mascota");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeDetalleCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Detalle", "Id Cliente", "Id Mascota"
            }
        ));
        jScrollPane1.setViewportView(tablaDeDetalleCM);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 600, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER DETALLE CLIENTE MASCOTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 510, 10));

        botonVerMascotas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerMascotas.setForeground(new java.awt.Color(0, 0, 0));
        botonVerMascotas.setText("ACEPTAR");
        botonVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMascotasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoDetalle2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMascotasActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerMascotasActionPerformed


    private void mostrarDetalleCM(){
        int cantidadDeElementos = controlador.cantidadDeDetalles();
        String [] encabezado = {"Id Detalle", "Id Cliente", "Id Mascota"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeDetalleCM.setModel(cabecera);
        TableModel tablaDeDetallesVista = tablaDeDetalleCM.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            DetalleCM detalle = controlador.listaDeDetalles().get(i);
            tablaDeDetalleCM.setValueAt(detalle.getIdDetalleCM(), i, 0);
            tablaDeDetalleCM.setValueAt(detalle.getIdCliente(), i, 1);
            tablaDeDetalleCM.setValueAt(detalle.getIdMascota(), i, 2);

        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerMascotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeDetalleCM;
    // End of variables declaration//GEN-END:variables
}
