/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import java.util.HashSet;
import java.util.Set;
import org.rodrigodiaz.controller.ControlDeCliente;
import org.rodrigodiaz.controller.ControlDeMascota;
import org.rodrigodiaz.model.Cliente;

/**
 *
 * @author rodro
 */
public class ViewCrearCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCrearUsuario
     */
    public ViewCrearCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblEstadoCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblTelefonoCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblDpiCliente = new javax.swing.JLabel();
        lblUsuarioCliente = new javax.swing.JLabel();
        checkEstadoCliente = new javax.swing.JCheckBox();
        lblContraseñaCliente = new javax.swing.JLabel();
        botonCrearCliente = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtDpiCliente = new javax.swing.JTextField();
        txtUsuarioCliente = new javax.swing.JTextField();
        txtContraseñaCliente = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Crear Cliente");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREAR CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCliente3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        lblEstadoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoCliente.setText("Estado");
        jPanel1.add(lblEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        lblNombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCliente.setText("Nombre");
        jPanel1.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, -1));

        lblApellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblApellidoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoCliente.setText("Apellido");
        jPanel1.add(lblApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, -1));

        lblTelefonoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoCliente.setText("Telefono");
        jPanel1.add(lblTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblEmailCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEmailCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailCliente.setText("Email");
        jPanel1.add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblDpiCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDpiCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblDpiCliente.setText("DPI");
        jPanel1.add(lblDpiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        lblUsuarioCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblUsuarioCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioCliente.setText("Usuario");
        jPanel1.add(lblUsuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        checkEstadoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoCliente.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoCliente.setText("Activo");
        jPanel1.add(checkEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 110, -1));

        lblContraseñaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblContraseñaCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseñaCliente.setText("Contraseña");
        jPanel1.add(lblContraseñaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        botonCrearCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCrearCliente.setForeground(new java.awt.Color(0, 0, 0));
        botonCrearCliente.setText("Crear");
        botonCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 90, 30));
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));
        jPanel1.add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, -1));
        jPanel1.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, -1));
        jPanel1.add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, -1));
        jPanel1.add(txtDpiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, -1));
        jPanel1.add(txtUsuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 130, -1));
        jPanel1.add(txtContraseñaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearClienteActionPerformed
        Cliente cliente = new Cliente();
        ControlDeCliente controlador = new ControlDeCliente();
        cliente.setNombreCliente(txtNombreCliente.getText());
        cliente.setApellidoCliente(txtApellidoCliente.getText());
        cliente.setTelefonoCliente(txtTelefonoCliente.getText());
        cliente.setEmailCliente(txtEmailCliente.getText());
        cliente.setDpiCliente(txtDpiCliente.getText());
        cliente.setUsuarioCliente(txtUsuarioCliente.getText());
        cliente.setContraseñaCliente(String.valueOf(txtContraseñaCliente.getPassword()));
        if (checkEstadoCliente.isSelected()) {
            cliente.setEstadoActivo(true);
        }else{
            cliente.setEstadoActivo(false);
        }
        
        controlador.agregarCliente(cliente);
        txtNombreCliente.setText("");
        txtApellidoCliente.setText("");
        txtTelefonoCliente.setText("");
        txtEmailCliente.setText("");
        txtDpiCliente.setText("");
        txtUsuarioCliente.setText("");
        txtContraseñaCliente.setText("");
        setVisible(false);

    }//GEN-LAST:event_botonCrearClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCliente;
    private javax.swing.JCheckBox checkEstadoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblContraseñaCliente;
    private javax.swing.JLabel lblDpiCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEstadoCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblUsuarioCliente;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JPasswordField txtContraseñaCliente;
    private javax.swing.JTextField txtDpiCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
