/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import org.rodrigodiaz.controller.ControlDeDetalleCM;
import org.rodrigodiaz.model.DetalleCM;

/**
 *
 * @author rodro
 */
public class ViewCrearDetalleCM extends javax.swing.JInternalFrame {
    DetalleCM detalle = new DetalleCM();
    ControlDeDetalleCM controlador = new ControlDeDetalleCM();
    

    /**
     * Creates new form ViewCrearDetalleCM
     */
    public ViewCrearDetalleCM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearMascota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        lblRazaMascota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdClienteDetalle = new javax.swing.JTextField();
        txtIdMascotaDetalle = new javax.swing.JTextField();
        botonCrearDetalle = new javax.swing.JButton();
        lblEstadoMascota = new javax.swing.JLabel();
        checkEstadoDetalleCM = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Crear Detalle Cliente Mascota");

        panelCrearMascota.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearMascota.setForeground(new java.awt.Color(204, 204, 204));
        panelCrearMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREAR DETALLE CLIENTE MASCOTA");
        panelCrearMascota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 320, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascota.setText("Id Cliente");
        panelCrearMascota.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        lblRazaMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazaMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblRazaMascota.setText("Id Mascota");
        panelCrearMascota.add(lblRazaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoDetalle2.png"))); // NOI18N
        panelCrearMascota.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panelCrearMascota.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, -1));
        panelCrearMascota.add(txtIdClienteDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, -1));
        panelCrearMascota.add(txtIdMascotaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        botonCrearDetalle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCrearDetalle.setForeground(new java.awt.Color(0, 0, 0));
        botonCrearDetalle.setText("Crear");
        botonCrearDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearDetalleActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonCrearDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 30));

        lblEstadoMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMascota.setText("Estado");
        panelCrearMascota.add(lblEstadoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        checkEstadoDetalleCM.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoDetalleCM.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoDetalleCM.setText("Activo");
        panelCrearMascota.add(checkEstadoDetalleCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearDetalleActionPerformed
        detalle.setIdCliente(Integer.parseInt(txtIdClienteDetalle.getText()));
        detalle.setIdMascota(Integer.parseInt(txtIdMascotaDetalle.getText()));
        
        if (checkEstadoDetalleCM.isSelected()) {
            detalle.setEstadoActivo(true);
        }else{
            detalle.setEstadoActivo(false);
        }
        controlador.agregarDetalleCM(detalle);
        
        txtIdClienteDetalle.setText("");
        txtIdMascotaDetalle.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCrearDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearDetalle;
    private javax.swing.JCheckBox checkEstadoDetalleCM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstadoMascota;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblRazaMascota;
    private javax.swing.JPanel panelCrearMascota;
    private javax.swing.JTextField txtIdClienteDetalle;
    private javax.swing.JTextField txtIdMascotaDetalle;
    // End of variables declaration//GEN-END:variables
}
