/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeMascota;
import org.rodrigodiaz.model.Mascota;

/**
 *
 * @author rodro
 */
public class ViewActualizarMascota extends javax.swing.JInternalFrame {
            ControlDeMascota controlador = new ControlDeMascota();


    /**
     * Creates new form ViewActualizarMascota
     */
    public ViewActualizarMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearMascota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        lblIdBuscarActualizar = new javax.swing.JLabel();
        lblColorMascota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdMascotaBuscarActualizar = new javax.swing.JTextField();
        txtColorMascotaActualizar = new javax.swing.JTextField();
        txtRazaMascotaActualizar = new javax.swing.JTextField();
        botonBuscarDetalleCD = new javax.swing.JButton();
        lblRazaMascota1 = new javax.swing.JLabel();
        txtNombreMascotaActualizar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonActualizarMascota = new javax.swing.JButton();
        lblEstadoMascota = new javax.swing.JLabel();
        checkEstadoMascota = new javax.swing.JCheckBox();
        botonCancelarActualizarMascota1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Actualizar Mascota");

        panelCrearMascota.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearMascota.setForeground(new java.awt.Color(204, 204, 204));
        panelCrearMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTUALIZAR MASCOTA");
        panelCrearMascota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascota.setText("Nombre Mascota");
        panelCrearMascota.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        lblIdBuscarActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdBuscarActualizar.setForeground(new java.awt.Color(0, 0, 0));
        lblIdBuscarActualizar.setText("Id a buscar");
        panelCrearMascota.add(lblIdBuscarActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblColorMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblColorMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblColorMascota.setText("Color Mascota");
        panelCrearMascota.add(lblColorMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoMascota2.png"))); // NOI18N
        panelCrearMascota.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panelCrearMascota.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 310, -1));
        panelCrearMascota.add(txtIdMascotaBuscarActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, -1));
        panelCrearMascota.add(txtColorMascotaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, -1));
        panelCrearMascota.add(txtRazaMascotaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, -1));

        botonBuscarDetalleCD.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarDetalleCD.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarDetalleCD.setText("BUSCAR");
        botonBuscarDetalleCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDetalleCDActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonBuscarDetalleCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 130, 30));

        lblRazaMascota1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazaMascota1.setForeground(new java.awt.Color(0, 0, 0));
        lblRazaMascota1.setText("Raza Mascota");
        panelCrearMascota.add(lblRazaMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        panelCrearMascota.add(txtNombreMascotaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, -1));
        panelCrearMascota.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, -1));

        botonActualizarMascota.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizarMascota.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizarMascota.setText("ACTUALIZAR");
        botonActualizarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarMascotaActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonActualizarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 140, 30));

        lblEstadoMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMascota.setText("Estado");
        panelCrearMascota.add(lblEstadoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        checkEstadoMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoMascota.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoMascota.setText("Activo");
        panelCrearMascota.add(checkEstadoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 110, -1));

        botonCancelarActualizarMascota1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarActualizarMascota1.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarActualizarMascota1.setText("CANCELAR");
        botonCancelarActualizarMascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActualizarMascota1ActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonCancelarActualizarMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarDetalleCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDetalleCDActionPerformed
        Mascota mascota = new Mascota();
        mascota.setIdMascota(Integer.parseInt(txtIdMascotaBuscarActualizar.getText()));
        mascota = controlador.buscarMascota(mascota);
        if (mascota != null) {
            txtNombreMascotaActualizar.setText(mascota.getNombreMascotaMascota());
            txtRazaMascotaActualizar.setText(mascota.getRazaMascota());
            txtColorMascotaActualizar.setText(mascota.getColorMascota());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarDetalleCDActionPerformed

    private void botonActualizarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarMascotaActionPerformed
        Mascota mascota = new Mascota();
        mascota.setIdMascota(Integer.parseInt(txtIdMascotaBuscarActualizar.getText()));
        mascota.setNombreMascotaMascota(txtNombreMascotaActualizar.getText());
        mascota.setRazaMascota(txtRazaMascotaActualizar.getText());
        mascota.setColorMascota(txtColorMascotaActualizar.getText());
        if (checkEstadoMascota.isSelected()) {
            mascota.setEstado(true);
        }else{
            mascota.setEstado(false);
        }
        
        controlador.actualizarMascota(mascota);
        
        txtIdMascotaBuscarActualizar.setText("");
        txtNombreMascotaActualizar.setText("");
        txtRazaMascotaActualizar.setText("");
        txtColorMascotaActualizar.setText("");
        setVisible(false);
        
    }//GEN-LAST:event_botonActualizarMascotaActionPerformed

    private void botonCancelarActualizarMascota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActualizarMascota1ActionPerformed
               txtIdMascotaBuscarActualizar.setText("");
        txtNombreMascotaActualizar.setText("");
        txtRazaMascotaActualizar.setText("");
        txtColorMascotaActualizar.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActualizarMascota1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarMascota;
    private javax.swing.JButton botonBuscarDetalleCD;
    private javax.swing.JButton botonCancelarActualizarMascota1;
    private javax.swing.JCheckBox checkEstadoMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblColorMascota;
    private javax.swing.JLabel lblEstadoMascota;
    private javax.swing.JLabel lblIdBuscarActualizar;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblRazaMascota1;
    private javax.swing.JPanel panelCrearMascota;
    private javax.swing.JTextField txtColorMascotaActualizar;
    private javax.swing.JTextField txtIdMascotaBuscarActualizar;
    private javax.swing.JTextField txtNombreMascotaActualizar;
    private javax.swing.JTextField txtRazaMascotaActualizar;
    // End of variables declaration//GEN-END:variables
}
