/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeCliente;
import org.rodrigodiaz.model.Cliente;

/**
 *
 * @author rodro
 */
public class ViewActualizarCliente extends javax.swing.JInternalFrame {
            ControlDeCliente controlador = new ControlDeCliente();


    /**
     * Creates new form ViewActualizarUsuario
     */
    public ViewActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblEstadoCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblApellidoCliente = new javax.swing.JLabel();
        lblTelefonoCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblDpiCliente = new javax.swing.JLabel();
        lblUsuarioCliente = new javax.swing.JLabel();
        checkEstadoActualizarCliente = new javax.swing.JCheckBox();
        lblContraseñaCliente = new javax.swing.JLabel();
        botonCancelarActualizarCliente = new javax.swing.JButton();
        txtIdBuscarActualizarCliente = new javax.swing.JTextField();
        txtApellidoActualizarCliente = new javax.swing.JTextField();
        txtTelefonoActualizarCliente = new javax.swing.JTextField();
        txtEmailActualizarCliente = new javax.swing.JTextField();
        txtDpiActualizarCliente = new javax.swing.JTextField();
        txtUsuarioActualizarCliente = new javax.swing.JTextField();
        txtContraseñaActualizarCliente = new javax.swing.JPasswordField();
        botonActualizarCliente = new javax.swing.JButton();
        lblNombreCliente1 = new javax.swing.JLabel();
        txtNombreActualizarCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonBuscarCliente = new javax.swing.JButton();

        setClosable(true);
        setTitle("Actualizar Usuario");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTUALIZAR CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCliente3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 310, -1));

        lblEstadoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoCliente.setText("Estado");
        jPanel1.add(lblEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        lblNombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCliente.setText("Id a buscar");
        jPanel1.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        lblApellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblApellidoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoCliente.setText("Apellido");
        jPanel1.add(lblApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 60, -1));

        lblTelefonoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoCliente.setText("Telefono");
        jPanel1.add(lblTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblEmailCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEmailCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailCliente.setText("Email");
        jPanel1.add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblDpiCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDpiCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblDpiCliente.setText("DPI");
        jPanel1.add(lblDpiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        lblUsuarioCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblUsuarioCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioCliente.setText("Usuario");
        jPanel1.add(lblUsuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        checkEstadoActualizarCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoActualizarCliente.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoActualizarCliente.setText("Activo");
        jPanel1.add(checkEstadoActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, -1));

        lblContraseñaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblContraseñaCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblContraseñaCliente.setText("Contraseña");
        jPanel1.add(lblContraseñaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        botonCancelarActualizarCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarActualizarCliente.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarActualizarCliente.setText("CANCELAR");
        botonCancelarActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActualizarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelarActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 130, 30));
        jPanel1.add(txtIdBuscarActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));
        jPanel1.add(txtApellidoActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, -1));
        jPanel1.add(txtTelefonoActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 130, -1));
        jPanel1.add(txtEmailActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, -1));
        jPanel1.add(txtDpiActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 130, -1));
        jPanel1.add(txtUsuarioActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));
        jPanel1.add(txtContraseñaActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, -1));

        botonActualizarCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizarCliente.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizarCliente.setText("ACTUALIZAR");
        botonActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 150, 30));

        lblNombreCliente1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreCliente1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCliente1.setText("Nombre");
        jPanel1.add(lblNombreCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, -1));
        jPanel1.add(txtNombreActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        botonBuscarCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarCliente.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarCliente.setText("BUSCAR");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActualizarClienteActionPerformed

        txtIdBuscarActualizarCliente.setText("");
        txtNombreActualizarCliente.setText("");
        txtApellidoActualizarCliente.setText("");
        txtTelefonoActualizarCliente.setText("");
        txtEmailActualizarCliente.setText("");
        txtDpiActualizarCliente.setText("");
        txtUsuarioActualizarCliente.setText("");
        txtContraseñaActualizarCliente.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActualizarClienteActionPerformed

    private void botonActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarClienteActionPerformed
        Cliente cliente = new Cliente();
        
        cliente.setIdCliente(Integer.parseInt(txtIdBuscarActualizarCliente.getText()));
        cliente.setNombreCliente(txtNombreActualizarCliente.getText());
        cliente.setApellidoCliente(txtApellidoActualizarCliente.getText());
        cliente.setTelefonoCliente(txtTelefonoActualizarCliente.getText());
        cliente.setEmailCliente(txtEmailActualizarCliente.getText());
        cliente.setDpiCliente(txtDpiActualizarCliente.getText());
        cliente.setUsuarioCliente(txtUsuarioActualizarCliente.getText());
        cliente.setContraseñaCliente(String.valueOf(txtContraseñaActualizarCliente.getPassword()));
        if (checkEstadoActualizarCliente.isSelected()) {
            cliente.setEstadoActivo(true);
        }else{
            cliente.setEstadoActivo(false);
        }
        
        controlador.actualizarCliente(cliente);

        txtIdBuscarActualizarCliente.setText("");
        txtNombreActualizarCliente.setText("");
        txtApellidoActualizarCliente.setText("");
        txtTelefonoActualizarCliente.setText("");
        txtEmailActualizarCliente.setText("");
        txtDpiActualizarCliente.setText("");
        txtUsuarioActualizarCliente.setText("");
        txtContraseñaActualizarCliente.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonActualizarClienteActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setIdCliente(Integer.parseInt(txtIdBuscarActualizarCliente.getText()));
        cliente = controlador.buscarCliente(cliente);
        if (cliente != null) {
            txtNombreActualizarCliente.setText(cliente.getNombreCliente());
            txtApellidoActualizarCliente.setText(cliente.getApellidoCliente());
            txtTelefonoActualizarCliente.setText(cliente.getTelefonoCliente());
            txtEmailActualizarCliente.setText(cliente.getEmailCliente());
            txtDpiActualizarCliente.setText(cliente.getDpiCliente());
            txtUsuarioActualizarCliente.setText(cliente.getUsuarioCliente());
            txtContraseñaActualizarCliente.setText(cliente.getContraseñaCliente());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCliente;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonCancelarActualizarCliente;
    private javax.swing.JCheckBox checkEstadoActualizarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApellidoCliente;
    private javax.swing.JLabel lblContraseñaCliente;
    private javax.swing.JLabel lblDpiCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEstadoCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreCliente1;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblUsuarioCliente;
    private javax.swing.JTextField txtApellidoActualizarCliente;
    private javax.swing.JPasswordField txtContraseñaActualizarCliente;
    private javax.swing.JTextField txtDpiActualizarCliente;
    private javax.swing.JTextField txtEmailActualizarCliente;
    private javax.swing.JTextField txtIdBuscarActualizarCliente;
    private javax.swing.JTextField txtNombreActualizarCliente;
    private javax.swing.JTextField txtTelefonoActualizarCliente;
    private javax.swing.JTextField txtUsuarioActualizarCliente;
    // End of variables declaration//GEN-END:variables
}
