/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import org.rodrigodiaz.controller.ControlDeDetalleCD;
import org.rodrigodiaz.model.DetalleCD;

/**
 *
 * @author rodro
 */
public class ViewCrearDetalleCD extends javax.swing.JInternalFrame {
    
        DetalleCD detalle = new DetalleCD();
        ControlDeDetalleCD controlador = new ControlDeDetalleCD();

    /**
     * Creates new form ViewCrearDetalleCD
     */
    public ViewCrearDetalleCD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearMascota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        lblRazaMascota = new javax.swing.JLabel();
        lblColorMascota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdCitaDetalle = new javax.swing.JTextField();
        txtIdServicioDetalle = new javax.swing.JTextField();
        txtIdDoctorDetalle = new javax.swing.JTextField();
        botonCrearDetalle = new javax.swing.JButton();
        lblEstadoMascota = new javax.swing.JLabel();
        checkEstadoDetalleCD = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Crear Detalle Cita Doctor");

        panelCrearMascota.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearMascota.setForeground(new java.awt.Color(204, 204, 204));
        panelCrearMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREAR DETALLE CITA DOCTOR");
        panelCrearMascota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascota.setText("Id Cita ");
        panelCrearMascota.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, -1));

        lblRazaMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazaMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblRazaMascota.setText("Id Doctor");
        panelCrearMascota.add(lblRazaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblColorMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblColorMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblColorMascota.setText("Id Servicio");
        panelCrearMascota.add(lblColorMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoDetalle2.png"))); // NOI18N
        panelCrearMascota.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panelCrearMascota.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, -1));
        panelCrearMascota.add(txtIdCitaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, -1));
        panelCrearMascota.add(txtIdServicioDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, -1));
        panelCrearMascota.add(txtIdDoctorDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        botonCrearDetalle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCrearDetalle.setForeground(new java.awt.Color(0, 0, 0));
        botonCrearDetalle.setText("Crear");
        botonCrearDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearDetalleActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonCrearDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 30));

        lblEstadoMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMascota.setText("Estado");
        panelCrearMascota.add(lblEstadoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        checkEstadoDetalleCD.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoDetalleCD.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoDetalleCD.setText("Activo");
        panelCrearMascota.add(checkEstadoDetalleCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearDetalleActionPerformed
        
        detalle.setIdCita(Integer.parseInt(txtIdCitaDetalle.getText()));
        detalle.setIdDoctor(Integer.parseInt(txtIdDoctorDetalle.getText()));
        detalle.setIdServicios(Integer.parseInt(txtIdServicioDetalle.getText()));
        
        if (checkEstadoDetalleCD.isSelected()) {
            detalle.setEstadoActivo(true);
        }else{
            detalle.setEstadoActivo(false);
        }
        controlador.agregarDetalleCD(detalle);

        txtIdCitaDetalle.setText("");
        txtIdDoctorDetalle.setText("");
        txtIdServicioDetalle.setText("");
        setVisible(false);

    }//GEN-LAST:event_botonCrearDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearDetalle;
    private javax.swing.JCheckBox checkEstadoDetalleCD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblColorMascota;
    private javax.swing.JLabel lblEstadoMascota;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblRazaMascota;
    private javax.swing.JPanel panelCrearMascota;
    private javax.swing.JTextField txtIdCitaDetalle;
    private javax.swing.JTextField txtIdDoctorDetalle;
    private javax.swing.JTextField txtIdServicioDetalle;
    // End of variables declaration//GEN-END:variables
}
