/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeCita;
import org.rodrigodiaz.model.Cita;

/**
 *
 * @author rodro
 */
public class ViewVerCita extends javax.swing.JInternalFrame {
    private ControlDeCita controlador = ControlDeCita.getInstancia();

    /**
     * Creates new form ViewVerCita
     */
    public ViewVerCita() {
        initComponents();
        mostrarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeCitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        botonVerCitas = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ver Cita");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id cita", "Fecha", "Hora", "Nombre Mascota", "Nombre Dueño", "Email", "Telefono", "Id servicio", "DPI", "Nit", "Costo Cita"
            }
        ));
        jScrollPane1.setViewportView(tablaDeCitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 740, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER CITA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 170, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 510, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCita2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        botonVerCitas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerCitas.setForeground(new java.awt.Color(0, 0, 0));
        botonVerCitas.setText("ACEPTAR");
        botonVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCitasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCitasActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerCitasActionPerformed

    
    private void mostrarCitas(){
        int cantidadDeElementos = controlador.cantidadDeCitas();
        String [] encabezado = {"Id", "Fecha", "Hora", "Nombre Mascota", "Nombre Dueño", "Email", "Telefono", "Id Servicio", "DPI", "Nit", "Costo"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeCitas.setModel(cabecera);
        TableModel tablaDeCitasVista = tablaDeCitas.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            Cita cita = controlador.listaDeCitas().get(i);
            tablaDeCitas.setValueAt(cita.getIdCita(), i, 0);
            tablaDeCitas.setValueAt(cita.getFechaCita(), i, 1);
            tablaDeCitas.setValueAt(cita.getHoraCita(), i, 2);
            tablaDeCitas.setValueAt(cita.getNombreMascotaCita(), i, 3);
            tablaDeCitas.setValueAt(cita.getNombreDueñoCita(), i, 4);
            tablaDeCitas.setValueAt(cita.getEmailDueñoCita(), i, 5);
            tablaDeCitas.setValueAt(cita.getTelefonoDueñoCita(), i, 6);
            tablaDeCitas.setValueAt(cita.getIdServicioCita(), i, 7);
            tablaDeCitas.setValueAt(cita.getDpiDueñoCita(), i, 8);
            tablaDeCitas.setValueAt(cita.getNitDueñoCita(), i, 9);
            tablaDeCitas.setValueAt(cita.getCostoCita(), i, 10);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeCitas;
    // End of variables declaration//GEN-END:variables
}
