package org.rodrigodiaz.view;

import org.rodrigodiaz.controller.ControlDeDoctor;
import org.rodrigodiaz.model.Doctor;

/**
 *
 * @author rodro
 */
public class ViewCrearDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCrearMedico
     */
    public ViewCrearDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreCliente4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidoMedico = new javax.swing.JLabel();
        lblTelefonoMedico = new javax.swing.JLabel();
        lblDIreccionMedico = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        lblDepartamentoMedico = new javax.swing.JLabel();
        ckkEstadoMedico = new javax.swing.JCheckBox();
        lblEstadoMedico = new javax.swing.JLabel();
        lblEspecialidadMedico = new javax.swing.JLabel();
        cbDepartamentoMedico = new javax.swing.JComboBox<>();
        txtNombreMedico = new javax.swing.JTextField();
        txtApellidoMedico = new javax.swing.JTextField();
        txtEspecialidadMedico = new javax.swing.JTextField();
        txtDireccionMedico = new javax.swing.JTextField();
        txtTelefonoMedico = new javax.swing.JTextField();
        botonCrearMedico = new javax.swing.JButton();

        lblNombreCliente4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreCliente4.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCliente4.setText("Nombre");

        setClosable(true);
        setTitle("Crear Medico");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREAR MEDICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoMedico3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        lblApellidoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblApellidoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoMedico.setText("Apellido");
        jPanel1.add(lblApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, -1));

        lblTelefonoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoMedico.setText("Telefono");
        jPanel1.add(lblTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 60, -1));

        lblDIreccionMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDIreccionMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDIreccionMedico.setText("Direccion");
        jPanel1.add(lblDIreccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, -1));

        lblNombreMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMedico.setText("Nombre");
        jPanel1.add(lblNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, -1));

        lblDepartamentoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDepartamentoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamentoMedico.setText("Departamento");
        jPanel1.add(lblDepartamentoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, -1));

        ckkEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ckkEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        ckkEstadoMedico.setText("Activo");
        jPanel1.add(ckkEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 70, -1));

        lblEstadoMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMedico.setText("Estado");
        jPanel1.add(lblEstadoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        lblEspecialidadMedico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEspecialidadMedico.setForeground(new java.awt.Color(0, 0, 0));
        lblEspecialidadMedico.setText("Especialidad");
        jPanel1.add(lblEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 90, -1));

        cbDepartamentoMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Peten", "Quetzaltenango", "Quiche", "Retalhuleu", "Sacatepequez", "San Marcos", "Santa Rosa", "Solola", "Suchitepequez", "Totonicapan", "Zacapa" }));
        jPanel1.add(cbDepartamentoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 110, -1));
        jPanel1.add(txtNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 130, -1));
        jPanel1.add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));
        jPanel1.add(txtEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 130, -1));
        jPanel1.add(txtDireccionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, -1));
        jPanel1.add(txtTelefonoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, -1));

        botonCrearMedico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCrearMedico.setForeground(new java.awt.Color(0, 0, 0));
        botonCrearMedico.setText("Crear");
        botonCrearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMedicoActionPerformed
        Doctor doctor = new Doctor();
        ControlDeDoctor controlador = new ControlDeDoctor();
        doctor.setNombreDoctor(txtNombreMedico.getText());
        doctor.setApellidoDoctor(txtApellidoMedico.getText());
        doctor.setTelefonoDoctor(txtTelefonoMedico.getText());
        doctor.setDireccionDoctor(txtDireccionMedico.getText());
        
        if (cbDepartamentoMedico.getSelectedItem().equals("Alta Verapaz")) {
            doctor.setIdDepartamento(1);
        }else if(cbDepartamentoMedico.getSelectedItem().equals("Baja Verapaz")){
            doctor.setIdDepartamento(2);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Chimaltenango")) {
            doctor.setIdDepartamento(3);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Chiquimula")) {
            doctor.setIdDepartamento(4);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("El Progreso")) {
            doctor.setIdDepartamento(5);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Escuintla")) {
            doctor.setIdDepartamento(6);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Guatemala")) {
            doctor.setIdDepartamento(7);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Huehuetenango")) {
            doctor.setIdDepartamento(8);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Izabal")) {
            doctor.setIdDepartamento(9);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Jalapa")) {
            doctor.setIdDepartamento(10);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Jutiapa")) {
            doctor.setIdDepartamento(11);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Peten")) {
            doctor.setIdDepartamento(12);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Quetzaltenango")) {
            doctor.setIdDepartamento(13);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Quiche")) {
            doctor.setIdDepartamento(14);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Retalhuleu")) {
            doctor.setIdDepartamento(15);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Sacatepequez")) {
            doctor.setIdDepartamento(16);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("San Marcos")) {
            doctor.setIdDepartamento(17);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Santa Rosa")) {
            doctor.setIdDepartamento(18);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Solola")) {
            doctor.setIdDepartamento(19);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Suchitepequez")) {
            doctor.setIdDepartamento(20);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Totonicapan")) {
            doctor.setIdDepartamento(21);
        }else if (cbDepartamentoMedico.getSelectedItem().equals("Zacapa")) {
            doctor.setIdDepartamento(22);
        }
        
        doctor.setEspecialidadDoctor(txtEspecialidadMedico.getText());
       if (ckkEstadoMedico.isSelected()) {
            doctor.setEstadoActivo(true);
        }else{
            doctor.setEstadoActivo(false);
        }
       
       controlador.agregarDoctor(doctor);
       
       txtNombreMedico.setText("");
       txtApellidoMedico.setText("");
       txtTelefonoMedico.setText("");
       txtDireccionMedico.setText("");
       txtEspecialidadMedico.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCrearMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearMedico;
    private javax.swing.JComboBox<String> cbDepartamentoMedico;
    private javax.swing.JCheckBox ckkEstadoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellidoMedico;
    private javax.swing.JLabel lblDIreccionMedico;
    private javax.swing.JLabel lblDepartamentoMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblEstadoMedico;
    private javax.swing.JLabel lblNombreCliente4;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblTelefonoMedico;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtDireccionMedico;
    private javax.swing.JTextField txtEspecialidadMedico;
    private javax.swing.JTextField txtNombreMedico;
    private javax.swing.JTextField txtTelefonoMedico;
    // End of variables declaration//GEN-END:variables
}
