/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeDetalleCM;
import org.rodrigodiaz.model.DetalleCM;

/**
 *
 * @author rodro
 */
public class ViewActualizarDetalleCM extends javax.swing.JInternalFrame {
        DetalleCM detalle = new DetalleCM();
    ControlDeDetalleCM controlador = new ControlDeDetalleCM();

    /**
     * Creates new form ViewActualizarDetalleCM
     */
    public ViewActualizarDetalleCM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearMascota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        lblRazaMascota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdBuscarDetalle = new javax.swing.JTextField();
        txtIdMascotaDetalle = new javax.swing.JTextField();
        botonCancelarActualizarDetalle = new javax.swing.JButton();
        lblEstadoMascota = new javax.swing.JLabel();
        checkEstadoDetalleCM = new javax.swing.JCheckBox();
        botonActualizarDetalle1 = new javax.swing.JButton();
        lblNombreMascota1 = new javax.swing.JLabel();
        txtIdClienteDetalle = new javax.swing.JTextField();
        botonBuscarDetalleCM = new javax.swing.JButton();

        setClosable(true);

        panelCrearMascota.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearMascota.setForeground(new java.awt.Color(204, 204, 204));
        panelCrearMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTUALIZAR DETALLE CLIENTE MASCOTA");
        panelCrearMascota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 370, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascota.setText("Id a Buscar");
        panelCrearMascota.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, -1));

        lblRazaMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRazaMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblRazaMascota.setText("Id Mascota");
        panelCrearMascota.add(lblRazaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoDetalle2.png"))); // NOI18N
        panelCrearMascota.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        panelCrearMascota.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 310, -1));
        panelCrearMascota.add(txtIdBuscarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, -1));
        panelCrearMascota.add(txtIdMascotaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, -1));

        botonCancelarActualizarDetalle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarActualizarDetalle.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarActualizarDetalle.setText("CANCELAR");
        botonCancelarActualizarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActualizarDetalleActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonCancelarActualizarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 30));

        lblEstadoMascota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEstadoMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoMascota.setText("Estado");
        panelCrearMascota.add(lblEstadoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        checkEstadoDetalleCM.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        checkEstadoDetalleCM.setForeground(new java.awt.Color(0, 0, 0));
        checkEstadoDetalleCM.setText("Activo");
        panelCrearMascota.add(checkEstadoDetalleCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, -1));

        botonActualizarDetalle1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonActualizarDetalle1.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizarDetalle1.setText("ACTUALIZAR");
        botonActualizarDetalle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDetalle1ActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonActualizarDetalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 30));

        lblNombreMascota1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascota1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascota1.setText("Id Cliente");
        panelCrearMascota.add(lblNombreMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, -1));
        panelCrearMascota.add(txtIdClienteDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        botonBuscarDetalleCM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarDetalleCM.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarDetalleCM.setText("BUSCAR");
        botonBuscarDetalleCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDetalleCMActionPerformed(evt);
            }
        });
        panelCrearMascota.add(botonBuscarDetalleCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActualizarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActualizarDetalleActionPerformed

        txtIdBuscarDetalle.setText("");
        txtIdClienteDetalle.setText("");
        txtIdMascotaDetalle.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarActualizarDetalleActionPerformed

    private void botonActualizarDetalle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDetalle1ActionPerformed
        detalle.setIdDetalleCM(Integer.parseInt(txtIdBuscarDetalle.getText()));
        detalle.setIdCliente(Integer.parseInt(txtIdClienteDetalle.getText()));
        detalle.setIdMascota(Integer.parseInt(txtIdMascotaDetalle.getText()));
        if (checkEstadoDetalleCM.isSelected()) {
            detalle.setEstadoActivo(true);
        }else{
            detalle.setEstadoActivo(false);
        }
        controlador.actualizarDetalleCM(detalle);
        
        txtIdBuscarDetalle.setText("");
        txtIdClienteDetalle.setText("");
        txtIdMascotaDetalle.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonActualizarDetalle1ActionPerformed

    private void botonBuscarDetalleCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDetalleCMActionPerformed
        DetalleCM detalle = new DetalleCM();
        detalle.setIdDetalleCM(Integer.parseInt(txtIdBuscarDetalle.getText()));
        detalle = controlador.buscarDetalleCM(detalle);
        if (detalle != null) {
            txtIdClienteDetalle.setText(String.valueOf(detalle.getIdCliente()));
            txtIdMascotaDetalle.setText(String.valueOf(detalle.getIdMascota()));
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarDetalleCMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDetalle1;
    private javax.swing.JButton botonBuscarDetalleCM;
    private javax.swing.JButton botonCancelarActualizarDetalle;
    private javax.swing.JCheckBox checkEstadoDetalleCM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstadoMascota;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblNombreMascota1;
    private javax.swing.JLabel lblRazaMascota;
    private javax.swing.JPanel panelCrearMascota;
    private javax.swing.JTextField txtIdBuscarDetalle;
    private javax.swing.JTextField txtIdClienteDetalle;
    private javax.swing.JTextField txtIdMascotaDetalle;
    // End of variables declaration//GEN-END:variables
}
