/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeServicios;
import org.rodrigodiaz.model.Servicios;

/**
 *
 * @author rodro
 */
public class ViewVerServicios extends javax.swing.JInternalFrame {
    private ControlDeServicios controlador = ControlDeServicios.getInstancia();

    /**
     * Creates new form ViewVerServicios
     */
    public ViewVerServicios() {
        initComponents();
        mostrarServicios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeServicio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        botonVerMascotas = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Ver Servicios");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Servicio", "Servicio", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaDeServicio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 540, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER SERVICIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 420, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoServicios2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        botonVerMascotas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerMascotas.setForeground(new java.awt.Color(0, 0, 0));
        botonVerMascotas.setText("ACEPTAR");
        botonVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMascotasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMascotasActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerMascotasActionPerformed

    
    private void mostrarServicios(){
        int cantidadDeElementos = controlador.cantidadDeServicios();
        String [] encabezado = {"Id", "Servicio", "Costo"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeServicio.setModel(cabecera);
        TableModel tablaDeServiciosVista = tablaDeServicio.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            Servicios servicio = controlador.listaDeServicios().get(i);
            tablaDeServicio.setValueAt(servicio.getIdServicio(), i, 0);
            tablaDeServicio.setValueAt(servicio.getServicios(), i, 1);
            tablaDeServicio.setValueAt(servicio.getCostoServicio(), i, 2);

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerMascotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeServicio;
    // End of variables declaration//GEN-END:variables
}
