/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.rodrigodiaz.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.rodrigodiaz.controller.ControlDeCita;
import org.rodrigodiaz.model.Cita;

/**
 *
 * @author rodro
 */
public class ViewEliminarCita extends javax.swing.JInternalFrame {
            ControlDeCita controlador = new ControlDeCita();


    /**
     * Creates new form ViewEliminarCita
     */
    public ViewEliminarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearCita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNombreMascotaCita = new javax.swing.JLabel();
        lblFechaCita = new javax.swing.JLabel();
        lblServicioCita = new javax.swing.JLabel();
        lblHoraCita = new javax.swing.JLabel();
        lblNombreDueñoCita = new javax.swing.JLabel();
        lblEmailCita = new javax.swing.JLabel();
        lblTelefonoCita = new javax.swing.JLabel();
        lblDpiCita = new javax.swing.JLabel();
        lblNitCita = new javax.swing.JLabel();
        botonCancelarEliminarCita = new javax.swing.JButton();
        txtFechaCita = new javax.swing.JTextField();
        txtHoraCita = new javax.swing.JTextField();
        txtIdBuscarMascotaEliminarCita = new javax.swing.JTextField();
        txtNitCita = new javax.swing.JTextField();
        txtNombreDueñoCita = new javax.swing.JTextField();
        txtEmailCita = new javax.swing.JTextField();
        txtTelefonoCita = new javax.swing.JTextField();
        txtDpiCita = new javax.swing.JTextField();
        cbServicioCita = new javax.swing.JComboBox<>();
        lblFechaCita1 = new javax.swing.JLabel();
        txtNombreMascotaCita1 = new javax.swing.JTextField();
        botonEliminarCita1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        botonBuscarCita = new javax.swing.JButton();

        setClosable(true);
        setTitle("Eliminar Cita");

        panelCrearCita.setBackground(new java.awt.Color(204, 255, 255));
        panelCrearCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ELIMINAR CITA");
        panelCrearCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoCita2.png"))); // NOI18N
        panelCrearCita.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        panelCrearCita.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 510, 10));

        lblNombreMascotaCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreMascotaCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMascotaCita.setText("Nombre Mascota");
        panelCrearCita.add(lblNombreMascotaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, -1));

        lblFechaCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCita.setText("Id a buscar");
        panelCrearCita.add(lblFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, -1));

        lblServicioCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblServicioCita.setForeground(new java.awt.Color(0, 0, 0));
        lblServicioCita.setText("Servicio");
        panelCrearCita.add(lblServicioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        lblHoraCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblHoraCita.setForeground(new java.awt.Color(0, 0, 0));
        lblHoraCita.setText("Hora");
        panelCrearCita.add(lblHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        lblNombreDueñoCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombreDueñoCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreDueñoCita.setText("Nombre Dueño");
        panelCrearCita.add(lblNombreDueñoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, -1));

        lblEmailCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblEmailCita.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailCita.setText("Email");
        panelCrearCita.add(lblEmailCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));

        lblTelefonoCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTelefonoCita.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefonoCita.setText("Telefono");
        panelCrearCita.add(lblTelefonoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, -1));

        lblDpiCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblDpiCita.setForeground(new java.awt.Color(0, 0, 0));
        lblDpiCita.setText("DPI");
        panelCrearCita.add(lblDpiCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 100, -1));

        lblNitCita.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNitCita.setForeground(new java.awt.Color(0, 0, 0));
        lblNitCita.setText("Nit");
        panelCrearCita.add(lblNitCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, -1));

        botonCancelarEliminarCita.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonCancelarEliminarCita.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelarEliminarCita.setText("CANCELAR");
        botonCancelarEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarEliminarCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonCancelarEliminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 130, 30));

        txtFechaCita.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechaCita.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaCita.setText("AAAA/MM/DD");
        txtFechaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaCitaMousePressed(evt);
            }
        });
        panelCrearCita.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, -1));

        txtHoraCita.setForeground(new java.awt.Color(0, 0, 0));
        txtHoraCita.setText("HH/MM/SS");
        txtHoraCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHoraCitaMousePressed(evt);
            }
        });
        panelCrearCita.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, -1));
        panelCrearCita.add(txtIdBuscarMascotaEliminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 130, -1));
        panelCrearCita.add(txtNitCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 130, -1));
        panelCrearCita.add(txtNombreDueñoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));
        panelCrearCita.add(txtEmailCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, -1));
        panelCrearCita.add(txtTelefonoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 130, -1));
        panelCrearCita.add(txtDpiCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 130, -1));

        cbServicioCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anestesiologo", "Cardiologia", "Cirugia", "Dermatologia", "Fisioterapia", "Neurologia", "Oftalmologia", "Oncologia", "Ortopedia", "Equinos" }));
        panelCrearCita.add(cbServicioCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 130, -1));

        lblFechaCita1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblFechaCita1.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCita1.setText("Fecha");
        panelCrearCita.add(lblFechaCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));
        panelCrearCita.add(txtNombreMascotaCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, -1));

        botonEliminarCita1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonEliminarCita1.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminarCita1.setText("ELIMINAR");
        botonEliminarCita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCita1ActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonEliminarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, 30));
        panelCrearCita.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 510, 10));

        botonBuscarCita.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonBuscarCita.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarCita.setText("BUSCAR");
        botonBuscarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCitaActionPerformed(evt);
            }
        });
        panelCrearCita.add(botonBuscarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCita, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarEliminarCitaActionPerformed
        txtFechaCita.setText("");
        txtHoraCita.setText("");
        txtNombreMascotaCita1.setText("");
        txtNombreDueñoCita.setText("");
        txtEmailCita.setText("");
        txtTelefonoCita.setText("");
        txtDpiCita.setText("");
        txtNitCita.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonCancelarEliminarCitaActionPerformed

    private void txtFechaCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaCitaMousePressed
        if (txtFechaCita.getText().equals("AAAA/MM/DD")) {
            txtFechaCita.setText("");
            txtFechaCita.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFechaCitaMousePressed

    private void txtHoraCitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraCitaMousePressed
        if (txtHoraCita.getText().equals("HH/MM/SS")) {
            txtHoraCita.setText("");
            txtHoraCita.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtHoraCitaMousePressed

    private void botonEliminarCita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCita1ActionPerformed
        Cita cita = new Cita();
        cita.setIdCita(Integer.parseInt(txtIdBuscarMascotaEliminarCita.getText()));
        controlador.ocultarCita(cita);
        
        txtFechaCita.setText("");
        txtHoraCita.setText("");
        txtNombreMascotaCita1.setText("");
        txtNombreDueñoCita.setText("");
        txtEmailCita.setText("");
        txtTelefonoCita.setText("");
        txtDpiCita.setText("");
        txtNitCita.setText("");
        setVisible(false);
    }//GEN-LAST:event_botonEliminarCita1ActionPerformed

    private void botonBuscarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCitaActionPerformed
        Cita cita = new Cita();
        cita.setIdCita(Integer.parseInt(txtIdBuscarMascotaEliminarCita.getText()));
        cita = controlador.buscarCita(cita);
        if (cita != null) {
            txtFechaCita.setText(cita.getFechaCita());
            txtHoraCita.setText(cita.getHoraCita());
            txtNombreMascotaCita1.setText(cita.getNombreMascotaCita());
            txtNombreDueñoCita.setText(cita.getNitDueñoCita());
            txtEmailCita.setText(cita.getEmailDueñoCita());
            txtTelefonoCita.setText(cita.getTelefonoDueñoCita());
            txtDpiCita.setText(cita.getDpiDueñoCita());
            txtNitCita.setText(cita.getNitDueñoCita());
        }else{
            JOptionPane.showMessageDialog(null, "El dato que buscar no se encuentra en la base de datos");
        }
    }//GEN-LAST:event_botonBuscarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCita;
    private javax.swing.JButton botonCancelarEliminarCita;
    private javax.swing.JButton botonEliminarCita1;
    private javax.swing.JComboBox<String> cbServicioCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDpiCita;
    private javax.swing.JLabel lblEmailCita;
    private javax.swing.JLabel lblFechaCita;
    private javax.swing.JLabel lblFechaCita1;
    private javax.swing.JLabel lblHoraCita;
    private javax.swing.JLabel lblNitCita;
    private javax.swing.JLabel lblNombreDueñoCita;
    private javax.swing.JLabel lblNombreMascotaCita;
    private javax.swing.JLabel lblServicioCita;
    private javax.swing.JLabel lblTelefonoCita;
    private javax.swing.JPanel panelCrearCita;
    private javax.swing.JTextField txtDpiCita;
    private javax.swing.JTextField txtEmailCita;
    private javax.swing.JTextField txtFechaCita;
    private javax.swing.JTextField txtHoraCita;
    private javax.swing.JTextField txtIdBuscarMascotaEliminarCita;
    private javax.swing.JTextField txtNitCita;
    private javax.swing.JTextField txtNombreDueñoCita;
    private javax.swing.JTextField txtNombreMascotaCita1;
    private javax.swing.JTextField txtTelefonoCita;
    // End of variables declaration//GEN-END:variables
}
