package org.rodrigodiaz.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rodrigodiaz.controller.ControlDeMascota;
import org.rodrigodiaz.model.Mascota;

/**
 *
 * @author rodro
 */
public class ViewVerMascota extends javax.swing.JInternalFrame {
    
    private ControlDeMascota controlador = ControlDeMascota.getInstancia();

    /**
     * Creates new form ViewVerMascota
     */
    public ViewVerMascota() {
        initComponents();
        mostrarMascotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeMascotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        botonVerMascotas = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ver Mascota");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Mascota", "Nombre", "Raza", "Color", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaDeMascotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 600, 240));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("VER MASCOTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 170, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 510, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rodrigodiaz/resource/iconoMascota2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        botonVerMascotas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonVerMascotas.setForeground(new java.awt.Color(0, 0, 0));
        botonVerMascotas.setText("ACEPTAR");
        botonVerMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMascotasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMascotasActionPerformed

        setVisible(false);
    }//GEN-LAST:event_botonVerMascotasActionPerformed

    
    private void mostrarMascotas(){
        int cantidadDeElementos = controlador.cantidadDeMascotas();
        String [] encabezado = {"Id", "Nombre", "Raza", "Color"};
        DefaultTableModel cabecera = new DefaultTableModel(encabezado, cantidadDeElementos);
        tablaDeMascotas.setModel(cabecera);
        TableModel tablaDeMascotasVista = tablaDeMascotas.getModel();
        for (int i = 0; i < cantidadDeElementos; i++) {
            Mascota Mascota = controlador.listaDeMascotas().get(i);
            tablaDeMascotas.setValueAt(Mascota.getIdMascota(), i, 0);
            tablaDeMascotas.setValueAt(Mascota.getNombreMascotaMascota(), i, 1);
            tablaDeMascotas.setValueAt(Mascota.getRazaMascota(), i, 2);
            tablaDeMascotas.setValueAt(Mascota.getColorMascota(), i, 3);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerMascotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDeMascotas;
    // End of variables declaration//GEN-END:variables
}
